import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_public/privacy-policy")({
  component: PrivacyPolicyPage,
});

export default function PrivacyPolicyPage() {
  return (
    <div className="text-black">
      <div className="container mx-auto px-4 py-16">
        {/* MAIN HEADER */}
        <div>
          <h1 className="mb-4 font-semibold text-3xl">Privacy Policy</h1>
          <p className="text-gray-500 text-sm dark:text-gray-400">
            Last updated: January 20, 2023
          </p>
          <p className="mt-6">
            This Privacy Policy describes Our policies and procedures on the
            collection, use, and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mt-6">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </div>

        {/* INTERPRETATION AND DEFINITIONS */}
        <div className="mt-12">
          <h2 className="mb-4 font-semibold text-2xl">
            Interpretation and Definitions
          </h2>
          <h3 className="mb-2 font-semibold text-xl">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="mt-8 mb-2 font-semibold text-xl">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="mt-4 ml-6 list-disc space-y-2">
            <li>
              <b>Account</b> means a unique account created for You to access
              our Service or parts of our Service.
            </li>
            <li>
              <b>Company</b> (referred to as either &quot;the Company &quot;,
              &quot;Our&quot; in this Agreement) refers to MillenniCare PBC, 800
              4th Street SW, Washington D.C., 20024 N812.
            </li>
            <li>
              <b>Cookies</b> are small files that are placed on Your computer,
              mobile device, or any other device by a website, containing the
              details of Your browsing history on that website among its many
              uses.
            </li>
            <li>
              <b>Country</b> refers to: District Of Columbia, United States.
            </li>
            <li>
              <b>Device</b> means any device that can access the Service such as
              a computer, a cellphone, or a digital tablet.
            </li>
            <li>
              <b>Personal Data</b> is any information that relates to an
              identified or identifiable individual.
            </li>
            <li>
              <b>Service</b> refers to the Website.
            </li>
            <li>
              <b>Service Provider</b> means any natural or legal person who
              processes the data on behalf of the Company.
            </li>
            <li>
              <b>Usage Data</b> refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <b>Website</b> refers to MillenniCare, accessible from{" "}
              <Button variant="link" asChild className="p-0">
                <Link to="/">
                  <p>https://millennicare.com</p>
                </Link>
              </Button>
            </li>
            <li>
              <b>You</b> means the individual accessing or using the Service, or
              the company, or other legal entity on behalf of which such
              individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>

        {/* COLLECTING AND USING YOUR PERSONAL DATA */}
        <div className="mt-12">
          <h2 className="mb-4 font-semibold text-2xl">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="mb-2 font-semibold text-xl">
            Types of Data Collected
          </h3>

          <h4 className="mt-8 mb-2 font-semibold text-lg">Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="mt-4 ml-6 list-disc space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, Zip/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="mt-8 mb-2 font-semibold text-lg">Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p className="mt-4">
            Usage Data may include information such as Your Device&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that You visit, the time and date
            of Your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>

          <h4 className="mt-8 mb-2 font-semibold text-lg">
            Tracking Technologies and Cookies
          </h4>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service.
          </p>
          <ul className="mt-4 ml-6 list-disc space-y-2">
            <li>
              <b>Cookies or Browser Cookies.</b> A cookie is a small file placed
              on Your Device. You can instruct Your browser to refuse all
              Cookies or to indicate when a Cookie is being sent. However, if
              You do not accept Cookies, You may not be able to use some parts
              of our Service.
            </li>
            <li>
              <b>Web Beacons.</b> Certain sections of our Service and our emails
              may contain small electronic files known as web beacons that
              permit the Company, for example, to count users who have visited
              those pages or opened an email and for other related website
              statistics.
            </li>
          </ul>

          <p className="mt-4">
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
            Cookies. Persistent Cookies remain on Your personal computer or
            mobile device when You go offline, while Session Cookies are deleted
            as soon as You close Your web browser.
          </p>
          <p className="mt-4">
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </p>
          <ul className="mt-4 ml-6 list-disc space-y-2">
            <li>
              <b>Necessary / Essential Cookies</b>
            </li>
            <ul className="ml-6 list-disc">
              <li>Type: Session Cookies</li>
              <li>Administered by: Us</li>
              <li>
                Purpose: These Cookies are essential to provide You with
                services available through the Website and to enable You to use
                some of its features.
              </li>
            </ul>
            <li>
              <b>Cookies Policy / Notice Acceptance Cookies</b>
            </li>
            <ul className="ml-6 list-disc">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>
                Purpose: These Cookies identify if users have accepted the use
                of cookies on the Website.
              </li>
            </ul>
            <li>
              <b>Functionality Cookies</b>
            </li>
            <ul className="ml-6 list-disc">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>
                Purpose: These Cookies allow us to remember choices You make
                when You use the Website, such as remembering your login details
                or language preference.
              </li>
            </ul>
          </ul>
        </div>
      </div>
    </div>
  );
}
