/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthcheck": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations["read_root_healthcheck_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify */
    post: operations["verify_auth_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Forgot Password */
    post: operations["forgot_password_auth_forgot_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Reset Password */
    patch: operations["reset_password_auth_reset_password_patch"];
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Token */
    post: operations["refresh_token_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current User */
    get: operations["get_current_user_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/resend-verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend Verification */
    post: operations["resend_verification_auth_resend_verification_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get_user_users__user_id__get"];
    put?: never;
    post?: never;
    /** Delete User */
    delete: operations["delete_user_users__user_id__delete"];
    options?: never;
    head?: never;
    /** Update User */
    patch: operations["update_user_users__user_id__patch"];
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users */
    get: operations["get_users_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/onboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Onboard User */
    post: operations["onboard_user_users_onboard_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/waitlists/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Waitlist */
    post: operations["create_waitlist_waitlists__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contacts/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Contact */
    post: operations["create_contact_contacts__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contacts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Contact */
    get: operations["get_contact_contacts__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Contacts */
    get: operations["get_contacts_contacts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth/{provider}/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Authorize
     * @description Initiate OAuth2 flow with a social provider.
     *
     *     For web apps: Returns authorization URL and the client redirects the user
     *     For mobile apps: Returns authorization URL, app redirect the user
     *
     *     Query Parameters:
     *     - provider: OAuth provider (apple, google)
     *     - role: User role
     *     - app_type: Application type (web, mobile)
     *
     *     Headers:
     *     - Origin: For web apps, the origin domain
     *     - User-Agent: For mobile detection
     *
     *     Example requests:
     *     - Web: GET /oauth/google/authorize?role=caregiver&app_type=web
     *     - Mobile: GET /oauth/google/authorize?role=careseeker&app_type=mobile
     */
    get: operations["authorize_oauth__provider__authorize_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Callback */
    get: operations["callback_oauth__provider__callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_login_auth_login_post */
    Body_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_onboard_user_users_onboard_post */
    Body_onboard_user_users_onboard_post: {
      gender: components["schemas"]["UserGenderEnum"];
      /**
       * Phonenumber
       * Format: phone
       */
      phoneNumber: string;
      /**
       * Birthdate
       * Format: date-time
       */
      birthdate: string;
      /**
       * Profilepicture
       * Format: binary
       */
      profilePicture: string;
    };
    /**
     * ContactPriorityEnum
     * @enum {string}
     */
    ContactPriorityEnum: "low" | "medium" | "high" | "urgent";
    /** ContactSchema */
    ContactSchema: {
      /** Fullname */
      fullName: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Message */
      message: string;
      /** Subject */
      subject: string;
      /** Userid */
      userId?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["ContactStatusEnum"];
      priority: components["schemas"]["ContactPriorityEnum"];
      /**
       * Submittedat
       * Format: date-time
       */
      submittedAt: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Updatedat */
      updatedAt?: string | null;
    };
    /**
     * ContactStatusEnum
     * @enum {string}
     */
    ContactStatusEnum: "pending" | "in_progress" | "resolved" | "closed";
    /** CreateContactSchema */
    CreateContactSchema: {
      /** Fullname */
      fullName: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Message */
      message: string;
      /** Subject */
      subject: string;
      /** Userid */
      userId?: string | null;
    };
    /** CreateWaitlistSchema */
    CreateWaitlistSchema: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Detail */
      detail: string;
    };
    /** ForgotPasswordSchema */
    ForgotPasswordSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RefreshTokenRequestSchema */
    RefreshTokenRequestSchema: {
      /** Refreshtoken */
      refreshToken: string;
    };
    /** RegisterSchema */
    RegisterSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Firstname */
      firstName: string;
      /** Lastname */
      lastName: string;
      /** Roles */
      roles: components["schemas"]["RoleEnum"][];
    };
    /** ResendVerificationSchema */
    ResendVerificationSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** ResetPasswordSchema */
    ResetPasswordSchema: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /**
     * RoleEnum
     * @enum {string}
     */
    RoleEnum: "admin" | "careseeker" | "caregiver";
    /** TokenResponse */
    TokenResponse: {
      /** Accesstoken */
      accessToken: string;
      /** Refreshtoken */
      refreshToken: string;
    };
    /** UpdateUserSchema */
    UpdateUserSchema: {
      /** Firstname */
      firstName?: string | null;
      /** Lastname */
      lastName?: string | null;
      /** Email */
      email?: string | null;
      /** Rolestoadd */
      rolesToAdd?: components["schemas"]["RoleEnum"][] | null;
      /** Rolestoremove */
      rolesToRemove?: components["schemas"]["RoleEnum"][] | null;
      /** Email Verified */
      email_verified: boolean | null;
    };
    /**
     * UserGenderEnum
     * @enum {string}
     */
    UserGenderEnum: "male" | "female" | "other" | "prefer_not_to_say";
    /** UserInformation */
    UserInformation: {
      gender?: components["schemas"]["UserGenderEnum"] | null;
      /** Phonenumber */
      phoneNumber?: string | null;
      /** Birthdate */
      birthdate?: string | null;
      /** Profilepicture */
      profilePicture?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Userid
       * Format: uuid
       */
      userId: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Updatedat */
      updatedAt?: string | null;
    };
    /** UserSchema */
    UserSchema: {
      /** Firstname */
      firstName: string;
      /** Lastname */
      lastName: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Emailverified
       * @default false
       */
      emailVerified: boolean | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Updatedat */
      updatedAt?: string | null;
    };
    /** UserWithInformationSchema */
    UserWithInformationSchema: {
      /** Firstname */
      firstName: string;
      /** Lastname */
      lastName: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Emailverified
       * @default false
       */
      emailVerified: boolean | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Updatedat */
      updatedAt?: string | null;
      profile?: components["schemas"]["UserInformation"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifySchema */
    VerifySchema: {
      /** Token */
      token: string;
    };
    /** WaitlistSchema */
    WaitlistSchema: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Contacted */
      contacted: boolean;
      /** Referralcode */
      referralCode?: string | null;
      /** Notifiedat */
      notifiedAt?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  read_root_healthcheck_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_auth_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifySchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forgot_password_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_password_auth_reset_password_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_token_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorDetail"];
        };
      };
    };
  };
  get_current_user_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserWithInformationSchema"];
        };
      };
    };
  };
  resend_verification_auth_resend_verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendVerificationSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_user_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_users_users_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  onboard_user_users_onboard_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_onboard_user_users_onboard_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInformation"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_waitlist_waitlists__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWaitlistSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WaitlistSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_contact_contacts__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateContactSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_contact_contacts__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the contact */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_contacts_contacts_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  authorize_oauth__provider__authorize_get: {
    parameters: {
      query: {
        /** @description User role */
        role: "careseeker" | "caregiver" | "admin";
        /** @description Application type, e.g. mobile or web */
        app_type: "web" | "mobile";
      };
      header: {
        "user-agent": string | null;
      };
      path: {
        provider: "apple" | "google";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  callback_oauth__provider__callback_get: {
    parameters: {
      query: {
        /** @description Authorization code */
        code: string;
        /** @description State parameter for CSRF protection */
        state: string;
      };
      header?: never;
      path: {
        provider: "apple" | "google";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
