/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicEulaRouteImport } from './routes/_public/eula'
import { Route as PublicContactUsRouteImport } from './routes/_public/contact-us'
import { Route as PublicAboutRouteImport } from './routes/_public/about'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEulaRoute = PublicEulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactUsRoute = PublicContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof PublicAboutRoute
  '/contact-us': typeof PublicContactUsRoute
  '/eula': typeof PublicEulaRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/contact-us': typeof PublicContactUsRoute
  '/eula': typeof PublicEulaRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact-us': typeof PublicContactUsRoute
  '/_public/eula': typeof PublicEulaRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/contact-us' | '/eula' | '/privacy-policy' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact-us' | '/eula' | '/privacy-policy' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/contact-us'
    | '/_public/eula'
    | '/_public/privacy-policy'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/eula': {
      id: '/_public/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof PublicEulaRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact-us': {
      id: '/_public/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicContactUsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactUsRoute: typeof PublicContactUsRoute
  PublicEulaRoute: typeof PublicEulaRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactUsRoute: PublicContactUsRoute,
  PublicEulaRoute: PublicEulaRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
